### ISSUE TITLE
Error message when running autoplot

### ISSUE THREAD

**Issue by mekamc** [dardisco/survMisc#18]
I'm having trouble with the survMisc 0.5.5 package using R version 3.4.4 and I'm wondering if someone can help me troubleshoot. When I run the following code, I get an error message:

> data("kidney", package="KMsurv")
> autoplot(survfit(Surv(time, delta) ~ type, data=kidney), type="fill")
Error in if (is.nan(times1[1])) times1 <- times : 
  argument is of length zero

Any idea how I can do to fix this issue?

Thanks!

**Comment by webbedfeet** [comment]
I'm getting the same error

**Comment by KarinaMarks** [comment]
Hello - I have done some digging and this issue appears to be occurring because of the line;
```
times1 <- switch(EXPR = timeTicks, 
    major = ggplot_build(g1)$layout$panel_ranges[[1]]$x.major_source, 
    minor = ggplot_build(g1)$layout$panel_ranges[[1]]$x.minor_source, 
    custom = NaN, 
    weeks = seq(from = min(x1), to = max(x1), by = 7L), 
    months = seq(from = min(x1), to = max(x1), by = 12L))
```
In the function `autoplot` - more specifically when argument `timeTicks` is left as default (`"major"`) or is specified as `"minor"`, then code `ggplot_build(g1)$layout$panel_ranges` is run - which no longer exists due to changes in ggplot2. 

To get around this, you can use the argument `timeTicks = "custom"` and then specify the x axis in the `times` argument.

For example;
```
library(survMisc)
data("kidney", package="KMsurv")

s1 <- survfit(Surv(time, delta) ~ type, data = kidney)
autoplot(s1, timeTicks = "custom", times= seq(1, 30, 3))
```

Hope this helps as a work around - but the underlying issue still needs to be fixed by changing what part of the ggplot object is being pointed to in the `switch` statement.

**Comment by mclements** [comment]
I have submitted a pull request that may address this issue: <https://github.com/dardisco/survMisc/pull/19>.

Sincerely, Mark.
